config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "welcome:show"
  resources :users, only: [:new, :create] do
    resources :recipes, only: [:new, :create, :index, :update, :edit, :show]
  end

  get '/recipes/ordered_by_name', to: 'recipes#name'
  get '/recipes/ordered_by_time', to: 'recipes#time'
  
  resources :recipes, only: [:show, :index, :destroy]
  

  get '/', to: "welcome#index", as: 'root'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/auth/github/callback' => 'sessions#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :quantities 
    has_many :recipes, through: :quantities 

end

app/models/quantity.rb
class Quantity < ApplicationRecord
    belongs_to :recipe
    belongs_to :ingredient
    accepts_nested_attributes_for :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :quantities
    has_many :ingredients, through: :quantities
    
    accepts_nested_attributes_for :quantities
    
    validates :name, presence: true
    validates :instructions, presence: true
    validates :description, presence: true
    validates :time, presence: true
    
    scope :ordered_by_name, -> { order(name: :asc) }
    scope :ordered_by_time, -> { order(time: :asc)}


    def quantities_attributes=(quant_att)
       self.quantities.destroy_all
        quant_att.each do |key, value|
             if value["ingredient_attributes"]["name"] != ""
                ingredient = Ingredient.find_or_create_by(name: value["ingredient_attributes"]["name"])
                self.quantities.build(amount: value["amount"], ingredient: ingredient)
            end
        end    
    end




   

end

app/models/user.rb
class User < ApplicationRecord
    
    validates :email, presence: true
    validates :email, uniqueness: true 
    has_many :recipes
    has_secure_password

    def self.find_or_create_by_omniauth(auth_hash)
        self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
       

        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    before_action :require_login
    
    def require_login
        redirect_to root_path unless session.include? :user_id
    end
    
    def index
        if params[:user_id] && current_user.id == params[:user_id].to_i
            @user = current_user
            @recipes = @user.recipes
        elsif params[:user_id]
            flash[:alert] = "You are not authorized to view this User's Recipes"
            redirect_to recipes_path
        else
            @recipes = Recipe.all
        end
    end


    def name
        @recipes = Recipe.ordered_by_name
    end

    def time
        @recipes = Recipe.ordered_by_time
    end

    def show
        @recipe = Recipe.find_by(id: params[:id])
    end

    def destroy
        recipe = Recipe.find(params[:id])
        recipe.destroy
        redirect_to recipe_path, notice: "deleted Recipe #{recipe.name}"
    end

    
    def new
        if params[:user_id] && current_user.id == params[:user_id].to_i
            @user = current_user
            @recipe = Recipe.new(user_id: params[:user_id])
                5.times do 
                    quantity = @recipe.quantities.build
                    quantity.build_ingredient       
            end
        else
            flash[:alert] = "You are not authorized to create a recipe with your account!"
            redirect_to recipes_path
        end
            
    end
    

    def create
        @user = User.find_by(id: params[:user_id])
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to user_recipe_path(current_user, @recipe)
        else
            5.times do 
                quantity = @recipe.quantities.build
                quantity.build_ingredient
            end 
            render :new
        end
    end

    def edit 
        if params[:user_id] && current_user.id == params[:user_id].to_i
            @user = current_user
            @recipe = @user.recipes.find_by(id: params[:id])
            if !@recipe
                flash[:alert] = "This recipe doesnt exist in your collection!"
                redirect_to user_recipe_path(@user)
            else
                render :edit
            end
        else
            flash[:alert] = "You are not authorized to edit this recipe!"
            redirect_to recipes_path
        end
    end

    def update
        @user = current_user 
        @recipe = Recipe.find_by(id: params[:id])
       if @recipe.update(recipe_params)
        redirect_to recipe_path(@recipe)
       else
        render :edit
       end
    end

    def destroy
        @recipe = Recipe.find_by(id: params[:id])
        @recipe.destroy
        redirect_to recipes_path     
    end

    def recipe_params
        params.require(:recipe).permit(:name, :user_id, :description, :time, :instructions, quantities_attributes: [:amount, ingredient_attributes: [:name]])
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create



        if auth_hash = request.env["omniauth.auth"]
            @user = User.find_or_create_by_omniauth(auth_hash)
            session[:user_id] = @user.id
            redirect_to user_recipes_path(@user)
        else

            @user = User.find_by(email: params[:session][:email]) 
            if @user && @user.authenticate(params[:session][:password])
                session[:user_id] = @user.id 
                redirect_to user_recipes_path(@user)
            else
                render :new
            end
        end
    end

    def destroy
        session.clear
        redirect_to '/'
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end

   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_recipes_path(@user)
        else
        
            render :new
        end
    end

    

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index 

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="/login">Login</a></li>
        <li><a href="/users/new">Signup</a></li>
            
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/logout">Logout</a></li>
       
      </ul>
    </div>
  </div><
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeRialsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <%= render partial: 'layouts/nav'%>
<nav class="navbar navbar-light bg-light">

 <% if current_user %>
    
    <a class="btn btn-outline-success" href="/users/<%=current_user.id%>/recipes" role="button">
      My Recipes </a>
    <a class="btn btn-outline-success" href="/recipes" role="button">
      All Recipes </a>

  <% else %>
    
   
  </form>
  <%end%>
</nav>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/recipes/_display.html.erb
<%= link_to "Create a Recipe", new_user_recipe_path(current_user) %>

<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
      <p><%= recipe.time %> Minutes</p>
      <% if current_user.id == recipe.user.id %>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_user_recipe_path(current_user, recipe) %></li>
        <li><%= link_to "Delete", recipe_path(recipe), data: {
          confirm: "Are you sure you want to delete: #{recipe.name}?"
        }, method: :delete %></li>
      </ul>
      <%end%>
    </div>
  <% end %>
</div>

app/views/recipes/_form.html.erb
 <% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      prohibited this recipe from being saved:
    </h2>
 
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for [@user, @recipe] do |f| %>
<%= f.hidden_field :user_id%>

  <p>Recipe Name: <%= f.text_field :name %></p>
  <p>Cook Time: <%= f.text_field :time %></p>
  <ul>
    <%= f.fields_for :quantities do |q| %>
    <li>
      Quantity: <%= q.text_field :amount %>
        <%= q.fields_for :ingredient do |ingredient|%>
            Ingredient: <%= ingredient.text_field :name %>
        <%end%>
    </li>

    <% end %>
<p>Instructions: <%= f.text_area :instructions %></p>
<p>Description: <%=f.text_area :description %></p>
  </ul>
  <%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit a Recipe</h1>

<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<% if flash[:alert] %>
<%= flash[:alert] %>
<%end%>
<% if @user %>
<h1><%= @user.email %>'s Recipes</h1>

<%= link_to "Create a Recipe", new_user_recipe_path(current_user) %>

<% else %>
<h1>All Recipes</h1>
<%= link_to "Filtered Recipes by Name", recipes_ordered_by_name_path %> 
<%= link_to "Filtered Recipes by Time", recipes_ordered_by_time_path %>
<%end%>
<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
      <% if current_user.id == recipe.user.id %>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_user_recipe_path(current_user, recipe) %></li>
       <%= form_tag recipe_path(recipe), method: "delete" do %>
    <%= submit_tag "Delete #{recipe.name}", :class => 'btn btn-danger' %>
  <% end %>
      </ul>
      <%end%>
    </div>
  <% end %>
</div>

app/views/recipes/name.html.erb
<h1> Ordered Recipes</h1>

<%= render :partial => 'display' %>

app/views/recipes/new.html.erb
<h1>Create a New Recipe</h1>

<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Description: <%=@recipe.description%></h2>
<h2>Cook Time: <%= @recipe.time  %> minutes</h2>

<p>Ingredients: <% @recipe.quantities.each do |quant| %> </p>
         <p><%= quant.amount %> x <%= quant.ingredient.name %> </p>
<% end %> 
<p>Instructions: <%=@recipe.instructions%></p>

<div>
 <div class="recipes">
  
      <% if current_user.id == @recipe.user.id %>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_user_recipe_path(current_user, @recipe) %></li>
        <%= form_tag recipe_path(@recipe), method: "delete" do %>
    <%= submit_tag "Delete #{@recipe.name}", :class => 'btn btn-danger' %>
  <% end %>
      </ul>
      <%end%>
    </div>
</div>

app/views/recipes/time.html.erb
<h1> Ordered Recipes</h1>

<%= render :partial => 'display' %>

app/views/users/new.html.erb
<h1>Welcome to Josh's Digital Recipe Book</h1>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :email %> <br>
<%= f.text_field :email %><br>
<%= f.label :password %> <br>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %> <br>
<%= f.password_field :password_confirmation %><br>

<%= f.submit %>

   

<%end%>

<%= link_to "Signin with GitHub", '/auth/github' %>

app/views/welcome/index.html.erb
<h1>Welcome to Josh's Recipes Book</h1>
<!--<a class="navbar-brand" href="/users/new">Sign Up</a>
<a class="navbar-brand" href="/login">Sign In</a>